title: My Jekyll Sit

url: "http://0.0.0.0:4000/CMS-Website"
url: "http://brisk88.github.io/CMS-Website"
baseurl: /CMS-Website/

permalink: pretty

collections:
    portfolio:
        output: true
    gallery:
        output: true
    altBlog:
        output: true
        
prose:
  siteurl: "http://brisk88.github.io/CMS-Website"
  media: 'images'
  ignore: 
    - index.html
  metadata:
    _posts:
      - name: "category"
        field:
          element: "text"
          value: "post"
      - name: "layout"
        field:
        	label: "Layout"
          element: "text"
          value: "generic"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Choose Tags"
          value: ""
     
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"